version: 2
updates:
  - package-ecosystem: "npm" # Can be 'npm', 'pip', 'maven', 'docker', etc.
    directory: "/"           # Root of the project (where your package.json is)
    schedule:
      interval: "weekly"     # Can be 'daily', 'weekly', or 'monthly'
